### ISSUE TITLE
Beam search evaluation for Transformer

### ISSUE THREAD

**Issue by caffeine-lab** [jelifysh/Image-Captioning#1]
Hey @jelifysh ,

Great implementation. Thanks a lot.
Is there an implementation with beam search for predicting the caption? Will be much helpful.

**Comment by tanishqgautam** [comment]
Hi,
I haven't implemented beam search as of yet for transformers.

**Comment by caffeine-lab** [comment]
@jelifysh , Thank you. If you can implement it would be much helpful.

**Comment by tanishqgautam** [comment]
Yes! will do it in the coming weeks!
